#Minecraft server properties
#Thu Oct 08 23:43:46 UTC 2026
accepts-transfers=false
allow-flight=false
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
chat-spam-threshold-seconds=10
command-spam-threshold-seconds=10
debug=false
difficulty=normal
enable-code-of-conduct=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=M83K4GmJb6hLE8szd6li3zeI02pI8msqVG00dsAO
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-chained-neighbor-updates=1000000
max-players=20
max-tick-time=60000
max-world-size=29999984
motd=§x§f§f§5§7§b§a👑 §x§f§f§8§0§5§fVEXORA §x§f§f§b§0§5§fSM P §x§7§b§6§d§f§f⚔ 
network-compression-threshold=256
online-mode=false
op-permission-level=4
pause-when-empty-seconds=-1
player-idle-timeout=0
prevent-proxy-connections=false
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=https\://cdn.minepack.fr/pack/43a6a8d4-d8a2-4112-824a-f4a113380041
resource-pack-id=43a6a8d4-d8a2-4112-824a-f4a113380041
resource-pack-prompt=Pack hosted by minepack.fr for free
resource-pack-sha1=0f40fde010332db7e4b6142d27db325696073cb5
server-ip=
server-port=25565
simulation-distance=5
spawn-protection=0
status-heartbeat-interval=0
sync-chunk-writes=true
text-filtering-config=
text-filtering-version=0
transport=raknet
use-native-transport=true
view-distance=5
white-list=false
